# Generated by Django 3.2.8 on 2021-10-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField()),
                ('fans', models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [django.db.models.aggregates.Count('fans')],
            },
        ),
    ]
